import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Header from "../components/organisms/Header";
import BgEllipse from "../components/atoms/BgEllipse";
import Info from "../components/organisms/Info";

export default function Home() {
  return (
    <>
      <Head>
        <title>I9 The World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px="10%" pos="relative" h="100vh">
        <Header />
        <Info />
        {/* <Box pos="absolute" right="0" top="0">
          <BgEllipse />
        </Box> */}
      </Box>
    </>
  );
}
