import Head from "next/head";
import HomeTemplate from "../components/templates/HomeTemplate";
import Process from "../components/templates/Process";

export default function Home() {
  const TITLE = "Transformamos a sua *<br>* *<b>ideia<b>* em *<b>negócio<b>*";
  const DESCRIPTION =
    "A I9 ajuda você a *<b>construir o seu produto<b>* e *<br>* coloca-lo no mercado, para  *<b>começar a faturar o<b>* *<br>* *<b>mais rápido possível.<b>*";

  return (
    <>
      <Head>
        <title>I9 The World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate
        title={TITLE}
        description={DESCRIPTION}
        menuItens={["HOME", "PORTFÓLIO", "PROCESSOS", "BLOG"]}
        callToActionLabel="VAMOS CONVERSAR"
      />
      <Process />
    </>
  );
}
